// <auto-generated />
using MeetingRoomBooking.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingRoomBooking.Api.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260722090315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("MeetingRoomBooking.Api.Features.Bookings.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "StartUtc", "EndUtc");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_TimeRange", "\"EndUtc\" > \"StartUtc\"");
                        });
                });

            modelBuilder.Entity("MeetingRoomBooking.Api.Features.Rooms.MeetingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeetingRooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_MeetingRooms_Capacity", "\"Capacity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Name = "Focus Room"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            Name = "Collaboration Room"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 12,
                            Name = "Board Room"
                        });
                });

            modelBuilder.Entity("MeetingRoomBooking.Api.Features.Bookings.Booking", b =>
                {
                    b.HasOne("MeetingRoomBooking.Api.Features.Rooms.MeetingRoom", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetingRoomBooking.Api.Features.Rooms.MeetingRoom", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
